[book]
authors = ["siriusmart"]
language = "en"
multilingual = false
src = "src"
title = "Basehunter Sero and the Twelve Dupe Stashes"
description = "Basehunter Sero and the Twelve Dupe Stashes is a legendary tale centered around Basehunter Sero, the mythical discoverer of bases, and his secretive list of dupe stashes known as the Dupe Stashes of the Round Table. The story encompasses themes of chivalry, loyalty, and adventure."

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/siriusmart/merlin/tree/master/docs"
edit-url-template = "https://github.com/siriusmart/merlin/edit/master/docs/{path}"
